application: headlineshow
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: html/site/favicon.ico
  upload: html/site/favicon.ico
  mime_type: image/x-icon

- url: /robots.txt
  static_files: html/site/robots.txt
  upload: html/site/robots.txt

- url: /sitemap.xml
  static_files: html/site/sitemap.xml
  upload: html/site/sitemap.xml

- url: /media/7
  static_dir: html/media

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"

- name: lxml
  version: latest

