application: headlineshow
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: html/static/favicon.ico
  upload: html/static/favicon.ico
  mime_type: image/x-icon

- url: /robots.txt
  static_files: html/static/robots.txt
  upload: html/static/robots.txt

- url: /sitemap.xml
  static_files: html/static/sitemap.xml
  upload: html/static/sitemap.xml

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"

